### PR TITLE
Adds tests to polling controller

### PR DESCRIPTION
**Pull request by rthbound**
After verifying tests passed, also addressed duplicated code reported by code climate.

### CODE REVIEW

**Comment by uu59** [comment]
> Use public_send instead

Are you doing that?

**Comment by rthbound** [comment]
@uu59 I was assuming `#installing_gems` and `#uninstalling_gems` were public methods, but it appears they are private:

> private method `installing_gems' called for #<PollingController:0xc1d5338>

**Comment by uu59** [comment]
Okay, they are helper methods defined at controller so its private method.

I'm merging this PR, thanks again :star:

**Comment by rthbound** [comment]
Nice, glad to pitch in

**Pull request merged**
