### PR TITLE
Release v1.0.0-alpha.1

### PR DESCRIPTION
**Pull request by okkez**

### CODE REVIEW

**Comment by gaui** [comment]
Wow, you are awesome @okkez 
Can I install via gem?

**Comment by okkez** [comment]
You can install via `gem i fluentd-ui --pre`.

**Comment by gaui** [comment]
@okkez One question, is it possible to run UI as a seperate container?

**Comment by okkez** [comment]
This fluentd-ui can manage the local fluentd instance.

**Pull request merged**
